POST http://localhost:8080/api/pos
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"id":0,"vendorid":1, "amount": 349.85,"podate": "", "items":[{"id":0, "poid":0,"price": 19.99,"qty":10,"productid": "bdi001","productname":""},{"id": 0,"poid":0, "price": 29.99,"qty":5, "productid": "jd001","productname":""}]}
###
